### ISSUE TITLE
教程偏移值寻找没看明白

### ISSUE THREAD

**Issue by qiopgh** [dantmnf/NCSIOverride#3]
你好，教程最后一步寻找偏移值实在是没看明白，请问图中的偏移值是0x30吗
<img width="1250" alt="屏幕截图 2021-10-11 031004" src="https://user-images.githubusercontent.com/30387662/136710012-cd06c4ee-819d-4ec3-b569-2b3e31b22d1c.png">

**Comment by qiopgh** [comment]
因为我设置好了之后没有效果所以来请教一下

**Comment by dantmnf** [comment]
打开 windbg 之后还要在里面打三行命令，`0:000> ` 开头的那几行。

**Comment by qiopgh** [comment]
> 打开 windbg 之后还要在里面打三行命令，`0:000> ` 开头的那几行。

多谢，我去试试

**Comment by qiopgh** [comment]
> 13.107.4.50 [www.msftconnecttest.com](http://www.msftconnecttest.com) hosts 加一行 就解决了 哪里用那么麻烦去改注册表 可用 ip 有 13.107.4.50 13.107.4.51 13.107.4.52 13.107.4.53 13.107.4.54 13.107.4.55 13.107.4.56

多谢 我用https://github.com/crazy-max/WindowsSpyBlocker改成了别的了
